test in regular CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,17 +16,16 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
+        # older versions of OS are set on purpose
         os:
           - ubuntu-22.04
-          - ubuntu-24.04
           - macos-14
-          - macos-15
           - windows-2022
-          - windows-2025
 
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+
 
       - name: Install Qt (Windows)
         if: runner.os == 'Windows'
@@ -49,6 +48,7 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y libgl1-mesa-dev libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 libxcb-cursor0
 
+
       - name: Configure CMake (Windows)
         if: runner.os == 'Windows'
         shell: pwsh
@@ -58,17 +58,81 @@ jobs:
         if: runner.os != 'Windows'
         run: cmake -B build -S src -DCMAKE_BUILD_TYPE=Release
 
+
       - name: Build
         run: cmake --build build --config Release --parallel
 
-      - name: Test executable exists (Linux/macOS)
-        if: runner.os != 'Windows'
-        run: test -f build/cremniy || test -f build/cremniy.app/Contents/MacOS/cremniy
+      - name: Upload executables
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ matrix.os }}
+          path: |
+            build/cremniy
+            build/cremniy.app/Contents/MacOS/cremniy
+            build/cremniy.exe
+          if-no-files-found: error
 
-      - name: Test executable exists (Windows)
+  test:
+    needs: build
+    name: Test on ${{ matrix.os }}
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        os:
+          # newer versions of OS
+          - ubuntu-24.04
+          - macos-15
+          - windows-2025
+
+    steps:
+      - name: Get executable (Linux)
+        if: runner.os == 'Linux'
+        uses: actions/download-artifact@v4
+        with:
+          name: Linux
+          path: build/cremniy
+
+      - name: Get executable (macOS)
+        if: runner.os == 'macOS'
+        uses: actions/download-artifact@v4
+        with:
+          name: macOS
+          path: build/cremniy.app/Contents/MacOS/cremniy
+
+      - name: Get executable (Windows)
+        if: runner.os == 'Windows'
+        uses: actions/download-artifact@v4
+        with:
+          name: Windows
+          path: build/cremniy.exe
+
+
+      - name: Test executable (Linux)
+        if: runner.os == 'Linux'
+        run: |
+          ./build/cremniy &
+          sleep 3
+          pkill cremniy
+        # pkill must fail if application failed to start (i.e. already died)
+
+      - name: Test executable (macOS)
+        if: runner.os == 'macOS'
+        run: |
+          ./build/cremniy.app/Contents/MacOS/cremniy &
+          sleep 3
+          pkill cremniy
+
+      - name: Test executable (Windows)
         if: runner.os == 'Windows'
         shell: pwsh
         run: |
-          if (!(Test-Path "build/Release/cremniy.exe")) {
-            throw "build/Release/cremniy.exe was not produced"
+          $p = Start-Process "build/Release/cremniy.exe" -PassThru
+
+          Start-Sleep -Seconds 3
+          if ($p.HasExited) {
+            Write-Error "Process exited too early"
+            exit 1
           }
+
+          Stop-Process -Id $p.Id
